//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineBatchDetail
    {
        public int ID { get; set; }
        public Nullable<int> medID { get; set; }
        public Nullable<int> batchID { get; set; }
        public int quantityImported { get; set; }
        public decimal importPrice { get; set; }
        public System.DateTime importDate { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual MedicineBatch MedicineBatch { get; set; }
    }
}
