//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> cusID { get; set; }
        public string message { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> sendDate { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
